# Generated by Django 3.1 on 2021-08-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
